// ============================================================================
// 🤖 Project 17: Researcher-Writer Agent Duo (Multi-Agent Systems with LangGraph.js)
// ============================================================================
//
// WHAT IS A MULTI-AGENT SYSTEM?
// In a Multi-Agent System, we break complex workflows down into multiple 
// specialized agents (e.g. Researcher, Writer) that collaborate to achieve a goal.
//
// WHAT IS LANGGRAPH?
// LangGraph is a library for building stateful, multi-actor applications with LLMs.
// It structures the interaction between agents as a directed graph:
// - Nodes: Represent agents (computation blocks).
// - Edges: Represent routing transitions between agents.
// - State: Shared memory passed between nodes.
//
// Graph flow in this demo:
// [Start] ──▶ (Researcher Node) ──▶ (Writer Node) ──▶ [End]
//
// ============================================================================

import express from "express";
import { ChatGoogleGenerativeAI } from "@langchain/google-genai";
import { StateGraph } from "@langchain/langgraph";
import "dotenv/config";

// ==========================================
// ⚙️ Configuration Settings
// ==========================================
const CONFIG = {
  PORT: 3000,
  MODEL_NAME: "gemini-3.1-flash-lite",
  TEMPERATURE: 0.7,
};

const app = express();
app.use(express.json());
app.use(express.static("public"));

// Initialize LLM model
const model = new ChatGoogleGenerativeAI({
  model: CONFIG.MODEL_NAME,
  apiKey: process.env.GEMINI_API_KEY,
  temperature: CONFIG.TEMPERATURE,
});

// ==========================================
// 🕸️ LangGraph Workflow Setup
// ==========================================

// 1. Define the shared state structure using channels config for LangGraph v0.0.26
//
// WHAT IS THIS?
// This defines the shared state structure (the global memory) of our graph.
// It contains three channels:
// - topic: The user's input topic.
// - researchNotes: Bullet points generated by the Researcher Agent.
// - draft: The final blog newsletter post created by the Writer Agent.
//
// WHY DO WE USE THIS?
// 1. "default: () => ''" defines the initial value (empty string).
// 2. "value: (x, y) => y ?? x" is the update reducer. It says: "If a node outputs
//    a new value (y), overwrite the old value (x) with the new one."
const channels = {
  topic: {
    value: (x, y) => y ?? x,
    default: () => "",
  },
  researchNotes: {
    value: (x, y) => y ?? x,
    default: () => "",
  },
  draft: {
    value: (x, y) => y ?? x,
    default: () => "",
  },
};

// 2. Define the Researcher node
//
// WHAT IS THIS?
// The Researcher agent node. Its sole job is to take the 'topic' from the graph state,
// call Gemini to do factual research, and save the result into 'researchNotes' inside state.
// Input: 'state' - The current graph state containing topic, researchNotes, and draft.
// Output: Returns an object containing the new researchNotes string to update the state.
async function researcherNode(state) {
  console.log(`🔍 Researcher Agent investigating: "${state.topic}"`);

  const prompt = `
    You are an expert academic researcher agent.
    Conduct in-depth research on the topic: "${state.topic}".
    Provide a comprehensive, bulleted summary of 4 key facts, recent developments, or stats.
    Be purely factual and objective.
  `;

  const response = await model.invoke(prompt);

  // Return the update to state
  return { researchNotes: response.content };
}

// 3. Define the Writer node
//
// WHAT IS THIS?
// The Writer agent node. It takes the topic and the 'researchNotes' compiled by the Researcher,
// calls Gemini to draft a structured blog post, and saves the final text into 'draft' inside state.
// Input: 'state' - The current graph state containing topic, researchNotes, and draft.
// Output: Returns an object containing the new draft string to update the state.
async function writerNode(state) {
  console.log(`✍️ Writer Agent drafting content based on research notes...`);

  const prompt = `
    You are a professional blog writer agent.
    Write an engaging, 2-paragraph newsletter update about the topic: "${state.topic}".
    
    Use the following research notes compiled by your colleague:
    ${state.researchNotes}
    
    Make it engaging, well-structured, and reader-friendly. Do not invent facts.
  `;

  const response = await model.invoke(prompt);

  // Return the update to state
  return { draft: response.content };
}

// 4. Assemble nodes and edges into the graph workflow
//
// WHAT IS THIS?
// This connects our agents (Researcher and Writer) into a sequential, multi-agent pipeline.
//
// HOW IT WORKS:
// 1. "new StateGraph({ channels })" creates a graph using our topic, notes, and draft state memory.
// 2. ".addNode("researcher", researcherNode)" registers the Researcher agent step.
// 3. ".addNode("writer", writerNode)" registers the Writer agent step.
// 4. ".addEdge("__start__", "researcher")" tells the graph to start with the Researcher agent.
// 5. ".addEdge("researcher", "writer")" connects the output of the Researcher to the input of the Writer.
// 6. ".addEdge("writer", "__end__")" terminates the graph execution once the Writer is finished.
const workflow = new StateGraph({ channels })
  .addNode("researcher", researcherNode)
  .addNode("writer", writerNode)
  .addEdge("__start__", "researcher")   // Entry edge
  .addEdge("researcher", "writer")       // Connects Researcher output to Writer
  .addEdge("writer", "__end__");         // Exit edge

// 5. Compile the graph
const appGraph = workflow.compile();

// ==========================================
// 👥 API Route
// ==========================================
app.post("/api/collaborate", async (req, res) => {
  try {
    const { topic } = req.body;
    if (!topic) return res.status(400).json({ error: "Topic is required" });

    console.log(`👥 Triggering Collaborative Multi-Agent Graph for: "${topic}"`);

    // Run the LangGraph execution
    const result = await appGraph.invoke({ topic: topic });

    res.json({
      topic: result.topic,
      researchNotes: result.researchNotes,
      draft: result.draft,
    });
  } catch (error) {
    console.error("Graph execution error:", error);
    res.status(500).json({ error: error.message });
  }
});

// ===============================
// Start Server
// ===============================
app.listen(CONFIG.PORT, () =>
  console.log(`👥 Multi-Agent Collaboration running at http://localhost:${CONFIG.PORT}`)
);
